version: "3.1"
services:
  mysql_phototour:
    container_name: mysql_phototour
    build: 
      context: .
      dockerfile: Dockerfile_db
    image: phototour-db
    ports: 
      - "9002:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - phototour_db_data:/var/lib/mysql
    mem_limit: 512m
  wordpress_phototour:
    container_name: wordpress_phototour
    build: 
      context: .
      dockerfile: Dockerfile_wordpress
    image: phototour-wordpress
    volumes:
      - ./wordpress_files:/var/www/html/
    ports: 
      - "8006:80"
    environment:
      WORDPRESS_DB_HOST: mysql_phototour:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    #volumes:
    #  - phototour_wordpress_data:/var/www/html
  phpmyadmin_phototour:
    container_name: phpmyadmin_phototour
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql_phototour:db
    ports:
      - 8007:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
volumes:
  phototour_db_data:
  phototour_wordpress_data: