version: "3.1"
services:
  mysql_photo-tour:
    container_name: mysql_photo-tour
    build: 
      context: .
      dockerfile: Dockerfile_db
    image: photo-tour-db
    ports: 
      - "9002:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - photo-tour_db_data:/var/lib/mysql
  wordpress_photo-tour:
    container_name: wordpress_photo-tour
    build: 
      context: .
      dockerfile: Dockerfile_wordpress
    image: photo-tour-wordpress
    volumes:
      - ./wordpress_files:/var/www/html/
    ports: 
      - "8006:80"
    environment:
      WORDPRESS_DB_HOST: mysql_photo-tour:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    #volumes:
    #  - photo-tour_wordpress_data:/var/www/html
  phpmyadmin_photo-tour:
    container_name: phpmyadmin_photo-tour
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql_photo-tour:db
    ports:
      - 8007:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
volumes:
  photo-tour_db_data:
  photo-tour_wordpress_data: